# Generated by Django 4.2.1 on 2023-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReflinkModel',
            fields=[
                ('reflink_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weigh', models.DecimalField(decimal_places=1, default=60, max_digits=4)),
            ],
        ),
    ]
