# Generated by Django 4.2.1 on 2023-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uses_coupon', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='reflinkmodel',
            name='weigh',
        ),
        migrations.AddField(
            model_name='reflinkmodel',
            name='uses_reflink',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
