# Generated by Django 4.2.1 on 2023-09-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_couponmodel_remove_reflinkmodel_weigh_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponModel',
            new_name='Coupon',
        ),
        migrations.RenameModel(
            old_name='ReflinkModel',
            new_name='Reflink',
        ),
    ]
