# Generated by Django 4.2.5 on 2023-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_rename_couponmodel_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_value_coupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type_coupon',
            field=models.CharField(choices=[('PE', 'percent'), ('AM', 'amount')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uses_coupon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='uses_reflink',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
