# Generated by Django 4.2.5 on 2023-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_coupon_max_value_coupon_coupon_type_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='value_coupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
