# Generated by Django 4.2.5 on 2023-09-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_coupon_value_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses_coupon',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=20, null=True),
        ),
    ]
