# Generated by Django 4.2.5 on 2023-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_coupon_max_uses_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='zero_amount',
            field=models.BooleanField(default=False, help_text='coupon resetting the amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses_coupon',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value_coupon',
            field=models.DecimalField(decimal_places=2, default=0, help_text='amount or percentage', max_digits=5),
        ),
    ]
