# Generated by Django 4.2.5 on 2023-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_coupon_zero_amount_alter_coupon_max_uses_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_date_use',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date_use',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
