# Generated by Django 4.2.5 on 2023-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_coupon_end_date_use_coupon_start_date_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='email_assignment',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
