# Generated by Django 4.2.5 on 2023-10-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_coupon_assigment_coupon_email_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('has_link', models.BooleanField(default=False)),
                ('link', models.CharField(default=None, max_length=1000, null=True)),
                ('text', models.CharField(default=None, max_length=255, null=True)),
                ('start_at', models.DateField(blank=True, default=None, null=True)),
                ('end_at', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
