# Generated by Django 4.2.5 on 2023-10-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
