# Generated by Django 4.2.5 on 2023-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0011_alter_coupon_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflink',
            name='link_reflink',
            field=models.TextField(default='reflink/<django.db.models.fields.AutoField>'),
        ),
    ]
