# Generated by Django 4.2.5 on 2023-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_reflink_link_reflink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_value_coupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='link_reflink',
            field=models.TextField(default='your reflink is domain + reflink/ + id reflinkworking at this :)'),
        ),
    ]
