# Generated by Django 4.2.5 on 2023-09-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exclussion',
            fields=[
                ('exclussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('exclussion_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, max_length=100)),
                ('weigh', models.DecimalField(decimal_places=1, default=60, max_digits=4)),
                ('injury', models.BooleanField(default=False)),
                ('training', models.BooleanField(default=False)),
                ('often_injury', models.CharField(choices=[('OM', 'one on mounth'), ('OY', 'one on year'), ('O5', 'one on 5 years'), ('NI', "i don't have injury")], default='NI', max_length=255)),
                ('often_training', models.CharField(choices=[('OM', 'one on mounth'), ('OY', 'one on year'), ('O5', 'one on 5 years'), ('NI', "i don't have training")], default='NI', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('email_user', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('email_creator', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='how do this exercise', null=True)),
                ('exercise_alert', models.TextField(blank=True, help_text='attenion to', null=True)),
                ('exercise_url', models.URLField(blank=True, help_text='link to video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.training')),
            ],
        ),
    ]
