# Generated by Django 4.2.5 on 2024-02-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('product_type', models.CharField(choices=[('OPP', 'one product phisical'), ('OPO', 'one product online'), ('PPP', 'personalized product plus'), ('PPR', 'personalized product random')], default='PPR', max_length=100)),
                ('product_items', models.IntegerField(default=3)),
                ('products_to_include', models.IntegerField(default=3, help_text='products to include with exclusion in mixer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('question_text', models.CharField(blank=True, max_length=255)),
                ('question_description', models.TextField(blank=True, default=None, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('text', 'Text - not active now'), ('button', 'Button'), ('choice', 'Choice'), ('integer', 'Integer'), ('category', 'Result Category Choice')], default='button', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('slug', models.CharField(blank=True, max_length=102, null=True)),
                ('questionnaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, max_length=100)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'verbose_name': 'Survey',
            },
        ),
        migrations.CreateModel(
            name='ResultCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default=None, help_text='empty slug is autocomplete', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, help_text='link to video', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResultCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('result_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultcategory')),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerResultCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('len_result', models.IntegerField(default=1)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('result_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_value', models.IntegerField(blank=True, default=None, help_text='>= min', null=True)),
                ('maximum_value', models.IntegerField(blank=True, default=None, help_text='< max', null=True)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('result_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultitem')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('result_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultitem')),
            ],
        ),
    ]
