# Generated by Django 4.2.5 on 2023-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclussion',
            name='maximum_repeat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exclussion',
            name='minimum_repeat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
