# Generated by Django 4.2.5 on 2024-02-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyResultCategoryItem',
        ),
    ]
