# Generated by Django 4.2.5 on 2024-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('choice', 'Choice'), ('button', 'Button'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
