# Generated by Django 4.2.5 on 2023-09-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exclussion_maximum_repeat_exclussion_minimum_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclussion',
            name='maximum_repeat',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='exclussion',
            name='minimum_repeat',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=4),
        ),
    ]
