# Generated by Django 4.2.5 on 2024-02-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_surveyresultcategoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResultCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('result_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultcategory')),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.questionnaire')),
            ],
        ),
    ]
