# Generated by Django 4.2.5 on 2024-02-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_result_category_surveyresultcategoryitem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresultcategoryitem',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer'),
        ),
    ]
