# Generated by Django 4.2.5 on 2024-02-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_surveyresultcategoryitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.resultcategory'),
        ),
    ]
