# Generated by Django 4.2.5 on 2024-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resultitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultitem',
            name='category',
        ),
        migrations.AddField(
            model_name='resultitem',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.resultcategory'),
        ),
    ]
