# Generated by Django 4.2.5 on 2024-02-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_resultitem_category_resultitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultitem',
            name='category',
        ),
        migrations.AddField(
            model_name='resultitem',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.resultcategory'),
        ),
    ]
