# Generated by Django 4.2.5 on 2024-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_questionnaire_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('text', 'Text'), ('choice', 'Choice'), ('button', 'Button')], default='button', max_length=100),
        ),
    ]
