# Generated by Django 4.2.5 on 2024-01-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('choice', 'Choice'), ('button', 'Button'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
