# Generated by Django 4.2.5 on 2024-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_surveyansweritem_category_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, null=True, to='core.product')),
            ],
        ),
    ]
