# Generated by Django 4.2.5 on 2024-01-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('choice', 'Choice'), ('button', 'Button')], default='button', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
    ]
