# Generated by Django 4.2.5 on 2024-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixerCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mixer_category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.mixercategory'),
        ),
    ]
