# Generated by Django 4.2.5 on 2024-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mixercategory_product_mixer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mixer_category',
            field=models.ManyToManyField(blank=True, default=None, to='core.mixercategory'),
        ),
    ]
