# Generated by Django 4.2.5 on 2024-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyansweritem',
            name='answer_value',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('button', 'Button'), ('integer', 'Integer'), ('choice', 'Choice'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
