# Generated by Django 4.2.5 on 2024-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_surveyansweritem_answer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Choice'), ('integer', 'Integer'), ('text', 'Text'), ('button', 'Button')], default='button', max_length=100),
        ),
    ]
