# Generated by Django 4.2.5 on 2024-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('button', 'Button'), ('integer', 'Integer'), ('choice', 'Choice'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
