# Generated by Django 4.2.5 on 2024-01-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('button', 'Button'), ('integer', 'Integer'), ('choice', 'Choice'), ('text', 'Text')], default='button', max_length=100),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
