# Generated by Django 4.2.5 on 2024-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_goal_slug_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('choice', 'Choice'), ('button', 'Button')], default='button', max_length=100),
        ),
    ]
