# Generated by Django 4.2.5 on 2024-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusionitem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='exclusionitem',
            name='exlusion',
        ),
        migrations.RemoveField(
            model_name='goalitem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='goalitem',
            name='goal',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('button', 'Button'), ('integer', 'Integer'), ('choice', 'Choice'), ('text', 'Text')], default='button', max_length=100),
        ),
        migrations.DeleteModel(
            name='Exclusion',
        ),
        migrations.DeleteModel(
            name='ExclusionItem',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GoalItem',
        ),
    ]
