# Generated by Django 4.2.5 on 2024-01-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_exclusionitem_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('button', 'Button'), ('choice', 'Choice'), ('integer', 'Integer')], default='button', max_length=100),
        ),
        migrations.CreateModel(
            name='AnswerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('result_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultitem')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('result_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resultitem')),
            ],
        ),
    ]
