# Generated by Django 4.2.5 on 2024-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_resultitem_resultorder_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('button', 'Button'), ('choice', 'Choice'), ('integer', 'Integer'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
