# Generated by Django 4.2.5 on 2024-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('button', 'Button'), ('choice', 'Choice'), ('text', 'Text')], default='button', max_length=100),
        ),
        migrations.AlterField(
            model_name='resultitem',
            name='slug',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
