# Generated by Django 4.2.5 on 2024-01-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_resultitem_description_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('text', 'Text'), ('choice', 'Choice'), ('button', 'Button')], default='button', max_length=100),
        ),
    ]
