# Generated by Django 4.2.5 on 2024-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_resultitem_name_alter_question_question_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultOrder',
            new_name='SurveyItem',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('button', 'Button'), ('integer', 'Integer')], default='button', max_length=100),
        ),
        migrations.AlterField(
            model_name='resultitem',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
