# Generated by Django 4.2.5 on 2024-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_resultorder_surveyitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyItem',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Choice'), ('button', 'Button'), ('integer', 'Integer'), ('text', 'Text')], default='button', max_length=100),
        ),
    ]
