# Generated by Django 4.2.5 on 2024-01-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_surveyitem_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('text', 'Text'), ('choice', 'Choice'), ('button', 'Button')], default='button', max_length=100),
        ),
    ]
