# Generated by Django 4.2.1 on 2023-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.DecimalField(blank=True, decimal_places=0, default='123456789', max_digits=9, null=True)),
                ('active_sub', models.BooleanField(default=False)),
                ('id_sub', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
            ],
        ),
    ]
