# Generated by Django 4.2.5 on 2024-01-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
