# Generated by Django 4.2.5 on 2024-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_delete_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
