# Generated by Django 4.2.1 on 2023-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userproxy_first_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproxy',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userproxy',
            name='price_base',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='userproxy',
            name='price_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userproxy',
            name='regulations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userproxy',
            name='regulations_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
