# Generated by Django 4.2.5 on 2023-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userproxy_last_name_userproxy_price_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproxy',
            name='regulations',
            field=models.BooleanField(default=False),
        ),
    ]
