# Generated by Django 4.2.5 on 2023-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userproxy_regulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproxy',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
