# Generated by Django 4.2.5 on 2023-10-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userproxy_first_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproxy',
            name='price_id',
        ),
    ]
