# Generated by Django 4.2.5 on 2023-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('pl', 'PL'), ('en', 'EN')], max_length=5)),
                ('is_active', models.BooleanField(default=False)),
                ('text_regulations', models.TextField(blank=True, null=True)),
                ('type_regulations', models.CharField(blank=True, choices=[('WEB', 'website'), ('MARK', 'marketing'), ('SUB', 'subscription'), ('ONE', 'one-off'), ('BUY', 'buy')], default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
