# Generated by Django 4.2.5 on 2023-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('1', 'system'), ('2', 'user')], max_length=5)),
                ('text_log', models.TextField(blank=True, null=True)),
                ('user_log', models.EmailField(blank=True, max_length=254, null=True)),
                ('status_log', models.CharField(choices=[('1', 'start'), ('2', 'end')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('PL', 'PLN'), ('EN', 'GBP')], default='PL', max_length=5)),
                ('valid_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('price_model', models.CharField(choices=[('ALL', 'Personalized'), ('BS', 'Business Small'), ('BB', 'Business Big')], default='ALL', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('pl', 'PL'), ('en', 'EN')], max_length=5)),
                ('is_active', models.BooleanField(default=False)),
                ('text_regulations', models.TextField(blank=True, null=True)),
                ('type_regulations', models.CharField(blank=True, choices=[('WEB', 'website'), ('MARK', 'marketing'), ('SUB', 'subscription'), ('ONE', 'one-off'), ('BUY', 'buy')], default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
