# Generated by Django 4.2.5 on 2024-01-02 17:42

from django.db import migrations, models
import django.db.models.deletion
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('1', 'system'), ('2', 'user')], max_length=5)),
                ('text_log', models.TextField(blank=True, null=True)),
                ('user_log', models.EmailField(blank=True, max_length=254, null=True)),
                ('status_log', models.CharField(choices=[('1', 'start'), ('2', 'end')], max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Activity Log',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('pl', 'PL'), ('en', 'EN')], max_length=5)),
                ('is_active', models.BooleanField(default=False)),
                ('text_regulations', models.TextField(blank=True, null=True)),
                ('type_regulations', models.CharField(blank=True, choices=[('WEB', 'website'), ('MARK', 'marketing'), ('SUB', 'subscription'), ('ONE', 'one-off'), ('BUY', 'buy')], default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Regulation',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, validators=[settings.models.validator_tag])),
                ('l_en', models.TextField()),
                ('l_pl', models.TextField(blank=True, default=None, null=True)),
                ('l_de', models.TextField(blank=True, default=None, null=True)),
                ('l_it', models.TextField(blank=True, default=None, null=True)),
                ('l_cz', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('question_sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Question Sequence',
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('sequence', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('question_sequence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settings.questionsequence')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('PL', 'PLN'), ('EN', 'GBP')], default='PL', max_length=5)),
                ('valid_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('price_model', models.CharField(choices=[('ALL', 'Personalized'), ('BS', 'Business Small'), ('BB', 'Business Big')], default='ALL', max_length=255)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
    ]
