# Generated by Django 4.2.5 on 2024-02-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_surveyansweritem_category_result'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionitem',
            name='if_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.answer'),
        ),
    ]
