# Generated by Django 4.2.5 on 2024-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_surveyansweritem_category_result'),
        ('settings', '0002_questionitem_if_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionitem',
            name='if_answer',
        ),
        migrations.AddField(
            model_name='questionitem',
            name='if_answer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.answer'),
        ),
    ]
