# Generated by Django 4.2.5 on 2023-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
