# Generated by Django 4.2.5 on 2023-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('1', 'system'), ('2', 'user')], max_length=5)),
                ('text_log', models.TextField(blank=True, null=True)),
                ('user_log', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
