# Generated by Django 4.2.5 on 2024-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_questionitem_if_answer_questionitem_if_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionitem',
            old_name='if_answer',
            new_name='answer',
        ),
    ]
