# Generated by Django 4.2.5 on 2024-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_surveyansweritem_category_result'),
        ('settings', '0004_rename_if_answer_questionitem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='answer',
            field=models.ManyToManyField(blank=True, default=None, to='core.answer'),
        ),
    ]
