# Generated by Django 4.2.5 on 2023-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='status_log',
            field=models.CharField(choices=[('1', 'start'), ('2', 'end')], default='1', max_length=5),
        ),
    ]
