# Generated by Django 4.2.5 on 2023-10-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_activitylog_status_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status_log',
            field=models.CharField(choices=[('1', 'start'), ('2', 'end')], max_length=5),
        ),
    ]
