# Generated by Django 4.2.5 on 2023-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_activitylog_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_model',
            field=models.CharField(choices=[('ALL', 'Personalized'), ('BS', 'Business Small'), ('BB', 'Business Big')], default='ALL', max_length=255),
        ),
    ]
