# Generated by Django 4.2.5 on 2024-03-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_questionitem_max_value_questionitem_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='max_value',
            field=models.CharField(blank=True, default=None, help_text='save this item in QuestionItem to update max value', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='min_value',
            field=models.CharField(blank=True, default=None, help_text='save this item in QuestionItem to update min value', max_length=5, null=True),
        ),
    ]
