# Generated by Django 4.2.5 on 2023-09-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_adress', models.EmailField(max_length=255)),
                ('item_status', models.CharField(choices=[('IC', 'Item Created'), ('IW', 'Item Verified')], default='IC', max_length=255)),
                ('editor_email', models.EmailField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('PL', 'Polish'), ('EN', 'English')], default='EN', max_length=255)),
            ],
            options={
                'ordering': ('item_id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('OC', 'Order Created'), ('WP', 'Waiting for Payment'), ('PA', 'Payment Accepted'), ('PE', 'Payment Error'), ('WA', 'Waiting for Acception'), ('OA', 'Order Accepted'), ('OS', 'Order Sended')], default='OC', max_length=255)),
                ('email_adress', models.EmailField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(choices=[('PL', 'Polish'), ('EN', 'English')], default='EN', max_length=255)),
                ('name_coupon', models.CharField(blank=True, max_length=15, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('pay_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('editor_email', models.EmailField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_id', models.CharField(blank=True, max_length=15, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('item_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.item')),
            ],
        ),
    ]
