# Generated by Django 4.2.5 on 2024-01-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='questionnaire_id',
        ),
    ]
