# Generated by Django 4.2.5 on 2024-02-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_remove_order_email_adress_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('order_id', models.IntegerField(blank=True, db_index=True)),
                ('order_status', models.CharField(choices=[('OC', 'Order Created'), ('WP', 'Waiting for Payment'), ('PA', 'Payment Accepted'), ('PE', 'Payment Error'), ('WA', 'Waiting for Acception'), ('PRE', 'Personalizations Error'), ('OA', 'Order Accepted'), ('OS', 'Order Sended'), ('OCA', 'Order Cancelled'), ('OR', 'Order Refounded')], default='OC', max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(choices=[('PL', 'Polish'), ('EN', 'English')], default='EN', max_length=255)),
                ('order_error', models.CharField(blank=True, max_length=255, null=True)),
                ('name_coupon', models.CharField(blank=True, max_length=15, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('pay_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('editor_email', models.EmailField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('visible', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
