# Generated by Django 4.2.5 on 2024-01-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_question_question_type'),
        ('orders', '0002_remove_order_questionnaire_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='questionnaire_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.questionnaire'),
        ),
    ]
