# Generated by Django 4.2.5 on 2024-01-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_questionnaire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
    ]
