# Generated by Django 4.2.5 on 2024-01-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_original_price_alter_order_pay_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_order',
        ),
    ]
