# Generated by Django 4.2.5 on 2024-01-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_question_question_type'),
        ('orders', '0008_orderresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_result', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderresult')),
                ('result_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.resultitem')),
            ],
        ),
    ]
