# Generated by Django 4.2.5 on 2024-01-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_question_question_type'),
        ('orders', '0009_orderresultitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresult',
            name='survey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.questionnaire'),
        ),
    ]
